language: node_js
node_js:
- '9'
branches:
  only:
  - master
install:
- npm install
before_script:
- git config --global user.name 'Or'
- git config --global user.email 'or@animaapp.com'
- |

       declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

       openssl aes-256-cbc \
         -K $encrypted_b604a4ee71b9_key \
         -iv $encrypted_b604a4ee71b9_iv \
         -in ".travis/id_rsa_dep.enc" \
         -out "$SSH_FILE" -d

       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config
script:
- "./node_modules/.bin/hexo generate -d"
before_install:
- openssl aes-256-cbc -K $encrypted_b604a4ee71b9_key -iv $encrypted_b604a4ee71b9_iv
  -in .travis/id_rsa_dep.enc -out .travis/id_rsa_dep -d

after_success:
  